### ISSUE TITLE
A different (and possibly better) search arguments format

### ISSUE THREAD

**Issue by z5kb** [SwapnilSoni1999/spotify-dl#160] opened 2022-05-13 14:51 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the search arguments spotifydl passes to youtube-dl, are in the following format (at least most of the time; example: when specifying --extra-search, the format is different):
`<song_name> - <album_name>`

When trying to download the album "Exhale" from the band "Thousand Foot Krutch" and reaching the song "Adrenaline", spotifydl passed the following arguments to youtube-dl:
`Adrenaline - Exhale`

The most popular item on YouTube [when searching with these arguments](https://www.youtube.com/results?search_query=Adrenaline+-+Exhale) is [this](https://www.youtube.com/watch?v=nhVrAVS53j8).
The expected result is [this](https://www.youtube.com/watch?v=h-HUQDEx9sM).

**Describe the solution you'd like**
I think it will be better if the search arguments are in the following format:
`<artist_name> - <song_name>`

I tried to figure out why you decided to go with the other format but I couldn't find a reason.

**Describe alternatives you've considered**
I tried passing in the `<artist_name>` as an extra search argument, which worked for this exact case, but when downloading another album ("The End Is Where We Begin", again by "Thousand Foot Krutch"), there was a song which was named after the album, which resulted in a problem.

When spotifydl tried to download the song "Be Somebody" after iterating through the other songs in the album, the search arguments looked like this ("tfk" is the band's short name; passed as an extra search argument):
`Be Somebody - The End Is Where We Begin tfk`

The most popular result on YouTube [when using these search arguments](https://www.youtube.com/results?search_query=%22Be+Somebody+-+The+End+Is+Where+We+Begin+tfk%22) was [the song named after the album](https://www.youtube.com/watch?v=IPQ7mvL5_04) instead of the expected result - ["Be Somebody"](https://www.youtube.com/watch?v=PGSvITdmrXM) (this was the third most popular item on YouTube - after the song named after the album and the album itself; see the first link in this paragraph).

**Additional context**
This is more like a note but if you don't want to change the format for the search arguments maybe you could add a way to specify the format through the command line. Example:
`--format "{artist} - {song}"`

**Comment by phyzical** [comment] 2022-05-14 07:09
@z5kb thanks for suggestion, from memory the reason i went `song - album` as due to the fact depending on how you request a download the "artist" was never the best reference due to how the spotify api worked i.e

say you request all songs from artist X, it will find all albums they are part of, which could result in an album in which they simply were collaborating  i.e for artist Y this means that when it goes to search the url for a song if we defaulted to the artist it would  search `song X - artist X` which should  have been `song X - artist Y` and thats the reason it favors album over artist 

the suggestion of a new flag is a good idea though so i will go ahead and implement it 👍 and then fallback to the default logic if the relevance is below 50%

from your testing did you find that `artist - song` / `album - song` is better than `song - artist` / `song - artist`? if so i can also flip the default "format" functionality

**Comment by z5kb** [comment] 2022-05-16 08:13
I understand why you made it this way, but why do you need to request all the songs of a given artist (from the Spotify API)? I thought you simply request the full album (at least in my case where you are trying to download an album; and isn't requesting to download all the albums of an artist more like a corner case? I think most people won't do that), which gives you all the songs in the album. I checked the API before I wrote my issue and as far as I saw each songs contains a list of the artists that created it (I may be wrong since I took a very brief look).

I didn't notice if `artist - song / album - song` is better than `song - artist / song - album` but if you want I can run some tests in the upcoming days and write back to you.

Also, I didn't quite get what you meant to say with "fallback to the default logic". Do you mean that you are going to remove the flag if most people don't use it?

I really like spotify-dl and it is my go-to program when download music. It's awesome how you are open to suggestions for improvement. Keep up the good work :)

**Comment by phyzical** [comment] 2022-05-16 08:26
@z5kb sorry so what i mean is it was standardized to work almost exactly the same irrelevant of what the user requests,
song, album, artist, show ect. if an album is requested it will only get the songs for that album (unless your noticing something else) so that it just gets a list of things to search for, the issue is that when you ask for a things artists, what i found is that it doesnt always return the best one as the first entry in the artists list, interms of a context for the youtube search, which is why album is tried first then fallback back to artist.

though granted you may be right as my usecase was from an artist and playlist usage, and the album usecase may always be the correct artist. but i think the new flag you have suggested will fix this issue going forward.

by fallback it simply means if the format provided finds nothing then itll just try to do what its already doing. the flag wont go anywhere.

the flag is implemented and will hopefully get merged sometime soon, though the maintainer can sometimes take a little while to find time if you want to give it a crack early feel free to checkout my pr and give it a try :)

**Closed** 2022-05-17 13:35 UTC
Labels: enhancement
