### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by answerquest** [SwapnilSoni1999/spotify-dl#145] opened 2021-12-17 04:26 UTC
**Describe the bug**
Unable to download an episode

**To Reproduce**
1. Command prompt:
```
spotifydl https://open.spotify.com/episode/0aZte37vtFTkYT7b0b04Qz
```
Output:
```
ℹ Starting processing of episode (https://open.spotify.com/episode/0aZte37vtFTkYT7b0b04Qz)
ℹ extracting episode set 1/1
ℹ Generating new access token
TypeError: Cannot read property 'name' of null
    at parseEpisode (file:///usr/local/lib/node_modules/spotify-dl/lib/api.js:221:19)
    at file:///usr/local/lib/node_modules/spotify-dl/lib/api.js:349:34
    at Array.map (<anonymous>)
    at extractEpisodes (file:///usr/local/lib/node_modules/spotify-dl/lib/api.js:349:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getEpisode (file:///usr/local/lib/node_modules/spotify-dl/util/get-songdata.js:48:11)
    at async run (file:///usr/local/lib/node_modules/spotify-dl/util/runner.js:160:25)
```

**Expected behavior**
Should have downloaded the episode (video / audio whichever)

**Desktop (please complete the following information):**
 - OS: Linux Mint Xfce 20.1 codename ulyssa
 - Version spotify-dl latest version 1.0.5 as per https://www.npmjs.com/package/spotify-dl , installed by command `sudo npm install -g spotify-dl`

**Additional context**
Might want to try skipping the name and proceed to download?

**Comment by Jolly-Pirate** [comment] 2022-01-02 14:29
Same issue, trying to download a video podcast.

**Comment by IsslamEl** [comment] 2022-01-05 11:08
same issue on Windows 10 Pro. spotifydl version 1.0.5

**Comment by phyzical** [comment] 2022-01-21 10:13
@Jolly-Pirate   this tool only has the ability to download mp3's not videos. (atleast at this time). 

It will also only search youtube to see if something exists, so if its partial its probably what is found on youtube based on whatever spotify names everything.

@IsslamEl  @answerquest this issue occurs when you do not provide auth as some episodes fail to return stuff from the spotify api for whatever reason.

@SwapnilSoni1999 it looks like the current version is behind the current codebase? this issue shouldnt be able to occur mind pushing a new update?

```
ℹ Starting processing of episode (https://open.spotify.com/episode/0aZte37vtFTkYT7b0b04Qz)
ℹ extracting episode set 1/1
ℹ Generating new access token
✖ Failed to find episode, you may need to use auth
✔ Finished!
```

**Comment by SwapnilSoni1999** [comment] 2022-01-26 17:36
Pushing the new update sorry for delaying my mental and physical health is not good since many weeks 
Apologies

**Comment by SwapnilSoni1999** [comment] 2022-01-26 21:03
Upgreaded to `1.0.7` please check and confirm if the issue is still there or not

**Comment by phyzical** [comment] 2022-01-27 03:56
@SwapnilSoni1999 never say sorry for taking care of yourself ;) can confirm its up to date now 👍 

![image](https://user-images.githubusercontent.com/5182053/151289367-86afc992-28d3-4d08-a972-a08d8831d0cc.png)

**Comment by SwapnilSoni1999** [comment] 2022-02-07 17:46
> @SwapnilSoni1999 never say sorry for taking care of yourself ;) can confirm its up to date now +1
> 
> ![image](https://user-images.githubusercontent.com/5182053/151289367-86afc992-28d3-4d08-a972-a08d8831d0cc.png)

Not fine since months tbh but just breathing. Doing whatever work I could but its okay and btw let me know if there are anymore issues left please I'm out of track

**Comment by phyzical** [comment] 2022-02-08 03:44
nope we are all good 👍 get better soon <3 feel free to close this

**Comment by SwapnilSoni1999** [comment] 2022-02-17 17:37
> nope we are all good +1 get better soon <3 feel free to close this (the ffmepg issue is just me being lazy with my pc when i tested it)

I cant thankyou enough for handling the entire project <3 I guess I'll never be fine but thats all I can live with. I wish to become a helpful asset for you let me know if you need anything. Again extremely appreciated

**Closed by SwapnilSoni1999** 2022-02-17 17:37 UTC
Labels: bug
