### ISSUE TITLE
Not Downloading

### ISSUE THREAD

**Issue by ShrayanshSharma6200** [SwapnilSoni1999/spotify-dl#134] opened 2021-08-30 06:58 UTC
/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/meow/index.js:1
import {dirname} from 'node:path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:877:16)
    at Module._compile (internal/modules/cjs/loader.js:928:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/lib/setup.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)

**Comment by phyzical** [comment] 2021-08-30 13:24
@SwapnilSoni1999 might bumping a new version i think this is a dupe of #132

**Closed** 2021-11-05 14:29 UTC
Labels: wontfix
